name: Deploy Backend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Private server via Public server (bastion) and redeploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PRIVATE_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          proxy_host: ${{ secrets.PUBLIC_HOST }}
          proxy_username: ${{ secrets.SSH_USER }}
          proxy_key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/cloudpj
            git pull
            docker compose -f docker-compose.local.yml up -d --build backend
